version: '3'
services:
    application:

        image: devagastya0/text_summary:v1
        ports:
          - "5000:5000"
        volumes: 
          - ./:/app
        command: ["python","/app/api.py"]
