version: '3'
services:
    application:
        image: devagastya0/text_summary:stable
        expose:
          - "5000"
        command: ["python","/app/api.py"]
        restart: always
        networks:
          - succinct

    webserver:
        image: devagastya0/succinct-nginx:stable
        restart: unless-stopped
        tty: true
        ports:
          - "80:80"
          - "443:443"
        networks:
          - succinct
networks:
  succinct:
    driver: bridge 
